# Exercise No.18

# Why does the following give an error
d = {"Name": "John", "Surname": "Smith"}
print(d["Smith"])


# Solution
# Because there is no key named "Smith," if we want to access that value we need to call its key "Surname."


